-- Popula marcas e modelos comuns do mercado brasileiro.
-- Rode depois de criar marcas_veiculos e modelos_veiculos.

with seed(marca, modelo) as (
  values
    ('Audi', 'A3'),
    ('Audi', 'A4'),
    ('Audi', 'Q3'),
    ('Audi', 'Q5'),
    ('Audi', 'Q7'),
    ('BMW', 'Série 3'),
    ('BMW', 'Série 5'),
    ('BMW', 'X1'),
    ('BMW', 'X3'),
    ('BMW', 'X5'),
    ('BMW', 'iX1'),
    ('BYD', 'Dolphin Mini'),
    ('BYD', 'Dolphin'),
    ('BYD', 'Yuan Pro'),
    ('BYD', 'Yuan Plus'),
    ('BYD', 'Song Pro'),
    ('BYD', 'Song Plus'),
    ('BYD', 'Seal'),
    ('Caoa Chery', 'Tiggo 5X'),
    ('Caoa Chery', 'Tiggo 7'),
    ('Caoa Chery', 'Tiggo 8'),
    ('Caoa Chery', 'Arrizo 6'),
    ('Chevrolet', 'Onix'),
    ('Chevrolet', 'Onix Plus'),
    ('Chevrolet', 'Tracker'),
    ('Chevrolet', 'Spin'),
    ('Chevrolet', 'Montana'),
    ('Chevrolet', 'S10'),
    ('Chevrolet', 'Equinox'),
    ('Chevrolet', 'Celta'),
    ('Chevrolet', 'Corsa'),
    ('Chevrolet', 'Classic'),
    ('Chevrolet', 'Prisma'),
    ('Chevrolet', 'Astra'),
    ('Chevrolet', 'Vectra'),
    ('Chevrolet', 'Meriva'),
    ('Chevrolet', 'Zafira'),
    ('Chevrolet', 'Agile'),
    ('Chevrolet', 'Cruze'),
    ('Citroen', 'C3'),
    ('Citroen', 'Aircross'),
    ('Citroen', 'Basalt'),
    ('Citroen', 'Jumpy'),
    ('Fiat', 'Strada'),
    ('Fiat', 'Argo'),
    ('Fiat', 'Mobi'),
    ('Fiat', 'Toro'),
    ('Fiat', 'Fastback'),
    ('Fiat', 'Pulse'),
    ('Fiat', 'Cronos'),
    ('Fiat', 'Fiorino'),
    ('Fiat', 'Uno'),
    ('Fiat', 'Palio'),
    ('Fiat', 'Siena'),
    ('Fiat', 'Grand Siena'),
    ('Fiat', 'Punto'),
    ('Fiat', 'Idea'),
    ('Fiat', 'Doblò'),
    ('Fiat', 'Bravo'),
    ('Fiat', 'Linea'),
    ('Ford', 'Ranger'),
    ('Ford', 'Territory'),
    ('Ford', 'Bronco Sport'),
    ('Ford', 'Mustang'),
    ('Ford', 'Maverick'),
    ('Ford', 'Fiesta'),
    ('Ford', 'Ka'),
    ('Ford', 'Focus'),
    ('Ford', 'EcoSport'),
    ('Ford', 'Fusion'),
    ('Ford', 'Courier'),
    ('GWM', 'Haval H6'),
    ('GWM', 'Ora 03'),
    ('GWM', 'Tank 300'),
    ('GWM', 'Poer'),
    ('Honda', 'HR-V'),
    ('Honda', 'City'),
    ('Honda', 'City Hatchback'),
    ('Honda', 'Civic'),
    ('Honda', 'Fit'),
    ('Honda', 'CR-V'),
    ('Honda', 'ZR-V'),
    ('Honda', 'WR-V'),
    ('Hyundai', 'HB20'),
    ('Hyundai', 'HB20S'),
    ('Hyundai', 'Creta'),
    ('Hyundai', 'Tucson'),
    ('Hyundai', 'Kona'),
    ('Jeep', 'Renegade'),
    ('Jeep', 'Compass'),
    ('Jeep', 'Commander'),
    ('Kia', 'Sportage'),
    ('Kia', 'Stonic'),
    ('Kia', 'Niro'),
    ('Kia', 'Bongo'),
    ('Mercedes-Benz', 'Classe A'),
    ('Mercedes-Benz', 'Classe C'),
    ('Mercedes-Benz', 'GLA'),
    ('Mercedes-Benz', 'GLB'),
    ('Mercedes-Benz', 'GLC'),
    ('Mercedes-Benz', 'Sprinter'),
    ('Mitsubishi', 'L200 Triton'),
    ('Mitsubishi', 'Pajero Sport'),
    ('Mitsubishi', 'Eclipse Cross'),
    ('Mitsubishi', 'Outlander'),
    ('Nissan', 'Kicks'),
    ('Nissan', 'Versa'),
    ('Nissan', 'Sentra'),
    ('Nissan', 'Frontier'),
    ('Peugeot', '208'),
    ('Peugeot', '2008'),
    ('Peugeot', 'Partner'),
    ('Ram', 'Rampage'),
    ('Ram', '1500'),
    ('Ram', '2500'),
    ('Ram', '3500'),
    ('Renault', 'Kwid'),
    ('Renault', 'Kardian'),
    ('Renault', 'Duster'),
    ('Renault', 'Oroch'),
    ('Renault', 'Master'),
    ('Toyota', 'Corolla'),
    ('Toyota', 'Corolla Cross'),
    ('Toyota', 'Hilux'),
    ('Toyota', 'SW4'),
    ('Toyota', 'Yaris'),
    ('Toyota', 'RAV4'),
    ('Toyota', 'Etios'),
    ('Toyota', 'Bandeirante'),
    ('Volkswagen', 'Polo'),
    ('Volkswagen', 'T-Cross'),
    ('Volkswagen', 'Tera'),
    ('Volkswagen', 'Nivus'),
    ('Volkswagen', 'Saveiro'),
    ('Volkswagen', 'Virtus'),
    ('Volkswagen', 'Taos'),
    ('Volkswagen', 'Amarok'),
    ('Volkswagen', 'Gol'),
    ('Volkswagen', 'Voyage'),
    ('Volkswagen', 'Fox'),
    ('Volkswagen', 'CrossFox'),
    ('Volkswagen', 'SpaceFox'),
    ('Volkswagen', 'Parati'),
    ('Volkswagen', 'Santana'),
    ('Volkswagen', 'Up'),
    ('Volkswagen', 'Bora'),
    ('Volkswagen', 'Jetta'),
    ('Volvo', 'EX30'),
    ('Volvo', 'XC40'),
    ('Volvo', 'XC60'),
    ('Volvo', 'XC90')
),
marcas as (
  insert into public.marcas_veiculos (nome)
  select distinct marca from seed
  on conflict (nome) do update set nome = excluded.nome
  returning id, nome
)
insert into public.modelos_veiculos (marca_id, nome)
select m.id, s.modelo
from seed s
join public.marcas_veiculos m on m.nome = s.marca
on conflict (marca_id, nome) do nothing;
